[package]
name = "srslte-sys"
version = "0.1.0"
authors = ["razorheadfx <razorhead.effect@gmail.com>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.37.0"
pkg-config = "0.3.11"

[features]
default = []
srslte_rf = []
